# Generated by Django 5.0.7 on 2024-08-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=200, null=True, verbose_name=' Your Full Name')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'felmale')], max_length=200, null=True, verbose_name=' Pick your gender')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=200, null=True, verbose_name=' Your Full Name')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'felmale')], max_length=200, null=True, verbose_name=' Pick your gender')),
                ('p_d_details', models.ManyToManyField(to='core.doctor', verbose_name='Choose Doctor')),
            ],
        ),
    ]
