# Generated by Django 5.0.7 on 2024-08-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='d_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='d_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='You name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='You adress'),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(max_length=50, null=True, verbose_name='Enter you age'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='You name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_d_details',
            field=models.ManyToManyField(to='core.doctor', verbose_name='patient doctor details'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Gender',
            field=models.CharField(choices=[('male', 'male'), ('Female', 'Female'), ('others', 'others')], max_length=200, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='patient',
            name='Gender',
            field=models.CharField(choices=[('male', 'male'), ('Female', 'Female'), ('others', 'others')], max_length=200, null=True, verbose_name='Gender'),
        ),
    ]
